services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_WEBHOOK_URL: ${BOT_WEBHOOK_URL}
      BOT_NAME: ${BOT_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      CHAT_API_KEY: ${CHAT_API_KEY}
      DB_URL: ${DB_URL}
    ports:
      - "5976:8080"


