services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_WEBHOOK_URL: ${BOT_WEBHOOK_URL}
      BOT_NAME: ${BOT_NAME}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      CHAT_API_KEY: ${CHAT_API_KEY}
      DB_URL: jdbc:postgresql://postgres:5432/weather_bot_db
    depends_on:
      - postgres
    networks:
      - backend
    ports:
      - "5976:8080"


networks:
  backend:
    driver: bridge