bot:
  token: ${BOT_TOKEN}
  webHook: ${BOT_WEBHOOK_URL}
  name: ${BOT_NAME}

server:
  address: 0.0.0.0
  ssl:
    enabled: false

spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

api:
  weather-api-key: ${WEATHER_API_KEY}
  ai-api-key: ${CHAT_API_KEY}

logging:
  level:
    org.example: debug
    dev.karmanov.library: debug